name: e712 CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [8.x, 10.x, 12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Yarn Globally
              run: npm install -g yarn@1.22.4
            - name: Install dependencies
              run: yarn install
            - name: Run TSLint
              run: yarn test:lint
            - name: Run Editorconfig
              run: yarn test:editorconfig
            - name: Run Mocha test suite
              run: yarn test:mocha
            - name: Run Build
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: build
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.github_token }}
